#!/usr/bin/env bash

action=$1
shift

function usage {
	echo "  $(basename $0)"
	echo "    Record all changes in Git repository located at $TODO_DIR."
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

$TODO_FULL_SH archive

cd "$TODO_DIR"
git diff && \
git commit -a -m "$(date +'%Y-%m-%d %H:%M:%S')"
